### ISSUE TITLE
Wrapping setjmp in greatest_save_context may be unsafe?

### ISSUE THREAD

**Issue by pmj** [silentbicycle/greatest#26]
While integrating the upstream longjmp-based assert implementation, I've just realised something:

Isn't making `greatest_save_context` a regular function and calling `setjmp` inside it invalid? (undefined behaviour) It's my understanding that you can't safely setjmp(), destroy the stack frame it was called from, and then longjmp back into it? So greatest_save_context really ought to be a macro, or possibly a forced-inline function.

The code as it stands seems to actually work in the cases I've thrown at it so far, probably because the return pointer in the test function's stack frame is in the same place as in greatest_save_context() in my case, and the return value (rax) is used as the same variable in either case.

            greatest_test_res res = greatest_save_context();
            if (res == GREATEST_TEST_RES_PASS) {
                res = TEST(); // <- return pointer actually causes greatest_save_context() to return here after longjmp?
            }

I haven't verified this theory at the assembly/register level, but I'm fairly sure the current use of setjmp/longjmp isn't actually legal, despite it appearing to work OK on my system. (OSX/x86-64)

I'll put together a suggested fix.

**Comment by silentbicycle** [comment]
You're right. I put that inside a function to make it easier to conditionally compile out, but I'm not sure that is portable as-is. It should probably be a macro instead (which will also make it more strongly internal-use-only than just a comment indicating such). Good catch.

**Comment by pmj** [comment]
OK, here's my suggested fix: 7b11a78

**Comment by silentbicycle** [comment]
That looks good to me. Cherry-picked to develop (as c5316b5).
