### ISSUE TITLE
implement GREATEST_ASSERT_INT_EQ

### ISSUE THREAD

**Issue by cohadar** [silentbicycle/greatest#28]
So failed test can report exact numbers that differ, not just that they do.

**Comment by silentbicycle** [comment]
This one is more complicated than it appears initially. How should the numbers be formatted -- "%d"? "%u"? "0x%04x"? Etc. I've experimented with various interfaces like GREATEST_ASSERT_EQ_FMT(exp, got, "0x%08x") but storing a message with the values will need dynamic allocation.

In the mean time, I added [GREATEST_ASSERT_EQUAL_Tm](https://github.com/silentbicycle/greatest/blob/master/greatest.h#L363), which will also work for comparing / printing out structs and other arbitrary types.

This could be done along similar lines -- print the values when the test fails, but don't store them in the message for printing during the suite summary.

**Comment by silentbicycle** [comment]
I just added this on the develop branch, following the pattern GREATEST_ASSERT_EQUAL_Tm uses. Does this work, for your purposes? https://github.com/silentbicycle/greatest/commit/70c41632461ad212b8192c0cda673226faf88ba7

**Comment by cohadar** [comment]
Nice idea with FMT.
It works great. 
You need a newline before "Expected:"

**Comment by cohadar** [comment]
GREATEST_ASSERT_EQUAL_Tm is too complicated to be useful.

It is better to add ASSERT for every primitive type in C language.
That way macros can even defensively cast the arguments to appropriate type.

I know it is a lot of repetitive coding, but imho it is worth it.
This might help: http://sourceforge.net/p/codereplicator/wiki/Home/

**Comment by silentbicycle** [comment]
GREATEST_ASSERT_EQUAL_Tm isn't intended for scalar types like int, but for comparing / printing arbitrary user-defined data structures without needing to alloc strings. It's overkill here, agreed.

I don't think adding boilerplate code for every primitive type fits greatest's design. I would rather provide a couple extensibility hooks and keep everything to a trivially portable, un-opinionated foundation. How the "expected X, got Y" message should be formatted is as dependent on usage context as variable type.

**Comment by cohadar** [comment]
Not all repetitive code is by definition boilerplate.
All I know is I would like to see actual values when my test fails.
How a framework does it is of no concern.

Even adding special case for INT is good enough for testing.
Integer type promotion will handle all types smaller than INT.

Also floating point assertions NEED a special case when you compare them because of rounding errors.
Most unit frameworks have 3-rd parameter on float asserts for rounding error tolerance.

Keeping things nice and simple is not always possible, in the end features always win over clean design.
