### ISSUE TITLE
Could dependency on time.h be configurable?

### ISSUE THREAD

**Issue by 1337hax** [silentbicycle/greatest#29]
I'm evaluating Greatest for usage on 8-bit atmega MCUs. So far it is excellent, I'm running the same test suits on PC (for comfortable debugging) and on avr (to test on final platform). It is so much better than minunit, which I've used before. 

However, I edited `greatest.h` to get rid of all time-related stuff. Sometimes on embedded devices there is no clock functionality, so it cannot track time. In these cases dependency on time.h is just waste of space and calculations on garbage times are waste of CPU cycles. 

I think that the best solution would be to have define such as this (maybe with better name) :
```
#define USE_CLOCK 1
```
Unsetting it  would strip out all time.h dependencies and time calculations. 
What do you think about that?

**Comment by silentbicycle** [comment]
Definitely. I've had a working branch for a while to restructure greatest for running on ATtinies, so I know where you're coming from. :) (I've been experimenting with non-stdio-based failure reporting, but haven't been happy with any designs yet. Any ideas?)

It would probably be best to branch off develop, and follow the pattern used for the other options, such as `GREATEST_USE_LONGJMP`.

**Comment by 1337hax** [comment]
Unfortunately I won't have time to code it. At least during couple of next weeks. 
About non-stdio-based failure reporting - I don't thing it is necessary to spend resources on that. Because:
1. Embedded devices are very different and there are many possible ways of sending information out of them: serial transmission by wire, blinking LEDs, radio transmission, ultrasounds etc. Speed of data transfer varies with all these channels. Sometimes it may be possible to only send information if all the tests passed or not. So you probably won't be able to design "one fits all" solution. It is library users' job to parse information about tests and send/log it in desired way.
2. It's easy to redirect standard output to user function and process it character-by-character.  So user of library can process information about test results there. Currently I'm sending every character to the PC, because I have my device connected to PC via serial port. Of course, parsing text information character-by-character may seem inconvenient, but I think it's the most reasonable way here.

**Comment by silentbicycle** [comment]
I was thinking of having a callback for notify_test_result that was called with a pass/fail/skip status, file:line info, and failure details. It would probably be a different enough implementation that it should be a distinct project, though.

**Comment by silentbicycle** [comment]
About this issue, how does bb498bd50c01835de2080c4fe7c781a7223e7b69 look?

I'll close the issue when I merge to master for the next release.

**Comment by 1337hax** [comment]
It looks good, thank you for taking my feedback into consideration.

**Comment by silentbicycle** [comment]
Merged to master, closed via 1.0.0 release. :)
