### ISSUE TITLE
README.md refers to "ASSERT_FAILm" when it should be "ASSERT_FALSEm"

### ISSUE THREAD

**Issue by tcarmelveilleux** [silentbicycle/greatest#30]
The README.md documentation talks about ASSERT_FALSE(cond) and **ASSERT_FAILm(msg, cond)**. However, the actual macro is ASSERT_**FALSEm**(msg,cond).

Took me about 1 minute to fix after reading the code when it didn't build, but seems like a trivial fix :)

**Comment by silentbicycle** [comment]
Good catch, thanks. Fixed by fd4d1fd.
