### ISSUE TITLE
Sign warning in greatest_do_assert_equal_t

### ISSUE THREAD

**Issue by jibsen** [silentbicycle/greatest#33]
I believe the `%d` should be `%u` in this line:

https://github.com/silentbicycle/greatest/blob/master/greatest.h#L669

I am getting a warning when compiling with MSVC.

**Comment by silentbicycle** [comment]
Agreed, good catch. (I don't have MSVC set up at the moment.) Is that the only warning you're seeing?

I'll check for other instances and do a patch version update soon. Sorry about the slow response - I've been traveling.

**Comment by jibsen** [comment]
With this fix, my test compiles cleanly with `/W3 /analyze`, which is my current target. If I increase the warning level to `/Wall`, I get a bunch of warnings, but mostly trivial stuff:

  - Padding added to structs
  - `__STDC_VERSION__` defaulting to 0 since MSVC is C89
  - Conditional expression is constant warning for every `do .. while (0)`
  - The missing void parameter list in `greatest_all_passed` already addressed in #31.

**Comment by silentbicycle** [comment]
Merged.

Thanks for letting me know about the MSVC warnings! I don't have that environment accessible currently.
