### ISSUE TITLE
Command-line parsing

### ISSUE THREAD

**Issue by jibsen** [silentbicycle/greatest#34]
I have a project where I would like to supply a command-line options to control the unit test. I could of course just omit `GREATEST_MAIN_BEGIN()` and parse the greatest options myself, but I wonder if it would be worth adding some way to handle this?

One option would be to stop the greatest parsing loop on encountering `--` (pretty standard), and then my code can pick up any arguments that come after.

**Comment by silentbicycle** [comment]
Treating -- as an end of arguments to greatest is a good idea.

**Comment by silentbicycle** [comment]
The pull request is merged. Any thoughts on also adjusting argv / argc so that the program under test just sees the arguments following the --, and argv[0] becomes its name?

Or maybe provide a function that does so, but don't call it by default?

**Comment by jibsen** [comment]
Thanks.

I thought about updating `argv` and `argc`, but was reluctant in case there were compilers that would frown upon it.

I don't think it is a problem according to the C standard though.

**Comment by silentbicycle** [comment]
I decided to leave argc and argv alone for the 1.1 release.
