### ISSUE TITLE
Issue using greenest

### ISSUE THREAD

**Issue by Overdrivr** [silentbicycle/greatest#43]
I am having trouble using `greenest` script, it is not recognized by the command line
I tried placing the file in the current folder the console is pointing to (along with .exe file) but it doesn't change a thing
I am using gradle as build system
Any hints on using that script ?

**Comment by silentbicycle** [comment]
greenest uses awk (a Unix scripting language). It won't work on Windows, unless you're in a Cygwin-ish environment. I'm quite rusty on setting that up, sorry.

(gradle probably won't make a difference here.)

**Comment by Overdrivr** [comment]
Could this be a solution ?
http://stackoverflow.com/questions/2353430/how-can-i-print-to-the-console-in-color-in-a-cross-platform-manner

**Comment by jibsen** [comment]
This has been discussed before #20 (and before #12), the problem is that not all terminals support ANSI escape codes. For instance the default Windows command prompt does not.
