### ISSUE TITLE
Clang 3.8 warning

### ISSUE THREAD

**Issue by jibsen** [silentbicycle/greatest#54]
I am getting a warning from Clang 3.8 when compiling with greatest (jibsen/brieflz#3). I tracked it back to the comparison at [line 651](https://github.com/jibsen/brieflz/blob/master/test/greatest.h#L651).

Is the comparison to `stdout` necessary, or could that line just be `fflush(GREATEST_STDOUT);`?

**Comment by silentbicycle** [comment]
Agreed, it should just be `fflush(GREATEST_STDOUT);`.
