### ISSUE TITLE
When GREATEST_USE_LONGJMP is set, RUN_TESTp causes segfault on any assert failure

### ISSUE THREAD

**Issue by tcarmelveilleux** [silentbicycle/greatest#58]
* OS: Windows 10, cygwin64, latest as of Aug 1st, 2017
* gcc version 5.4.0 targetting x86_64 target

Repro steps:
* Add `-DGREATEST_USE_LONGJMP` to compiler command line
* Run a test suite with complex code (deep function calls, dynamically allocated buffers), of which several tests are run with RUN_TESTp.
* Hard to repro with trivial tests, as there is no state to clobber.

When GREATEST_USE_LONGJMP is set, `setjmp()` (through `GREATEST_SAVE_CONTEXT()`) is only called in the `RUN_TEST` case and never in the `RUN_TEST1`/`RUN_TESTp` cases.

**Comment by silentbicycle** [comment]
Good find! I'm planning on posting a new release in the next few days, and will try to address this first.

**Comment by silentbicycle** [comment]
Fixed by PR #59 (again, thanks). This issue will get closed when the current `develop` branch is released.
