### ISSUE TITLE
ability to avoid duplicate test names

### ISSUE THREAD

**Issue by soul4soul** [silentbicycle/greatest#63]
I feel greatest needs a method for avoiding duplicate test names. I personally have 2 scenarios where this would be helpful.

1. Visually getting a overview of results is difficult when many tests are named the same and only a few of them are failing. 

2. I use TeamCity for continuous integration. I was looking to expanded the CI builds to run some basic regression testing. All of my tests use greatest. greatest support is not integrated into TeamCity but they have a method for [reporting test results on the fly](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingTests). I created a powershell script which interprets greatest print statements and creates the necessary TeamCity messages. Usage looks like `mytests.exe -v | greatest2teamcity.ps1`. One of the notes in the TeamCity documentation is that it's highly recommend to have unique suite+test names. Currently I solved this problem by keeping a counter of duplicate test names and appending that count amount to the end of the test name when duplicates are detected.

In my use of the greatest test framework I regularly use the following programming paradigms.

```
RUN_TEST1(MyFirstTest, AN_ENUM_TYPE_A);
RUN_TEST1(MyFirstTest, AN_ENUM_TYPE_B);
RUN_TEST1(MyFirstTest, AN_ENUM_TYPE_C);
RUN_TEST1(MyFirstTest, AN_ENUM_TYPE_D);
RUN_TEST1(MyFirstTest, AN_ENUM_TYPE_E);
RUN_TEST1(MyFirstTest, AN_ENUM_TYPE_F);
```
--OR--
```
TEST ASpecialTest(U8BIT u8Resolution)
{
    /*
    Do great things with u8Resolution
    */

    PASS();
}

void ASpecialTest_iterator()
{
    U8BIT u8Resolution;

    for (u8Resolution = 8; u8Resolution < 98; u8Resolution++)
    {
        RUN_TEST1(ASpecialTest, u8Resolution);
    }
}

SUITE(my_suite)
{
    ASpecialTest_iterator();
}
```

Both of these generate a long list of outputs that look something like
```
PASS MyFirstTest:  (1 ticks, 0.000 sec)
PASS MyFirstTest:  (1 ticks, 0.000 sec)
FAIL MyFirstTest:  (0 ticks, 0.000 sec)
PASS MyFirstTest:  (1 ticks, 0.000 sec)
PASS MyFirstTest:  (0 ticks, 0.000 sec)
PASS MyFirstTest:  (1 ticks, 0.000 sec)
PASS MyFirstTest:  (0 ticks, 0.000 sec)
```

One possible solution would be for greatest to have some built in functionality for looping through a range of variables and possible appending the variables value to the end of the test name. This still may not solve this issue for me as some of my "iterator functions" have up to 4 nested for loops.

Another possible solution would be to create additional marcos to the already existing GREATEST_RUN_TEST, GREATEST_IGNORE_TEST, and GREATEST_RUN_TEST1. Three new macros would take in a string argument for an extended name.

For example I have the following in a working example
```
/* Run a test in the current suite with one void * argument,
 * which can be a pointer to a struct with multiple arguments. 
 * Defined with an extended test name */
#define GREATEST_RUN_TEST1_EXT_NAME(TEST, ENV, EXT_NAME)                \
    do {                                                                \
        if (greatest_test_pre(#TEST) == 1) {                            \
            enum greatest_test_res res = GREATEST_SAVE_CONTEXT();       \
            if (res == GREATEST_TEST_RES_PASS) {                        \
                res = TEST(ENV);                                        \
            }                                                           \
            greatest_test_post(#TEST, EXT_NAME, res);                   \
        }                                                               \
    } while (0)

/* Run a test in the current suite with one void * argument,
 * which can be a pointer to a struct with multiple arguments. */
#define GREATEST_RUN_TEST1(TEST, ENV)                                   \
    GREATEST_RUN_TEST1_EXT_NAME(TEST, ENV, "")
```

**Comment by silentbicycle** [comment]
I've tried to address this before, but haven't found a solution I'm happy with yet. It becomes even more of an issue once test shuffling is in use, or when the output is being consumed by another system (such as CI).

Unfortunately, `snprintf` isn't available in C89, and while I could add `GREATEST_RUN_TESTx_EXT_NAME` for C99, that adds several new macros in combination with the other choices. Most of them would probably be one-line wrappers with a "" or NULL argument for the optional suffix, but there may be an option that avoids adding several more macros.

Taking an optional string argument seems like a better approach, rather than attempting to do any suffix construction in greatest itself (or appending a distinct but generally meaningless counter).

**Comment by silentbicycle** [comment]
How about adding a function that sets a suffix for the next test run (which is then cleared)? That wouldn't lead to a combinatorial explosion of `RUN_TEST_*` macros, and would nicely fit in a loop, table iterator, or other construction that repeatedly calls a parametric test.

**Comment by silentbicycle** [comment]
This will appear as `greatest_set_test_suffix(const char *suffix)` in the next release.

**Comment by soul4soul** [comment]
This feature is working well for me. I deleted my private fork and moved back to the mainline.

**Comment by silentbicycle** [comment]
Excellent! I find it really useful too, especially combined with `-t` and `-x`.
