### ISSUE TITLE
Elapsed time is based on `clock`, could improve accuracy

### ISSUE THREAD

**Issue by silentbicycle** [silentbicycle/greatest#65]
The elapsed time printouts are based on `clock`, but could use `gettimeofday`, `clock_gettime`, etc. after checking whether the appropriate symbols are defined. This would give more accurate elapsed wall clock time.

**Comment by silentbicycle** [comment]
This is particularly noticeable if the test forks worker processes. `gettimeofday` is probably fine, though, with a fallback on `clock()`. No need for a second feature macro check for things like `clock_gettime(CLOCK_MONOTONIC, &time);`.

**Comment by silentbicycle** [comment]
Wrapping the time types for `clock` and `gettimeofday` may not be worth the trouble.

**Comment by soul4soul** [comment]
I find greatest timekeeping features to be rather useless. It's not consistent between Windows and Linux. It's not accurate compared to wall time. For example one of my test programs tasks about 15 minutes on the wall clock. On Windows, Greatest says it takes 450 seconds or about 7 minutes. On Linux, Greatest says it takes 0.050 seconds.

It would be nice to have accurate elapsed time but I'm not pining for it. In fact, once my test program is integrated into a CI system it won't even be a problem anymore. The CI system keeps its own records of how long each step takes to execute.
