### ISSUE TITLE
Have the option to raise SIGABRT on test failure

### ISSUE THREAD

**Issue by fsaintjacques** [silentbicycle/greatest#71]
One handy feature (I find) of cmocka is that it raises a SIGABRT on a test failure. Paired with gdb, this will directly drop you in the failing line.

Would you accept a patch that introduce an optional flag `-a` (would imply `-f`) which raises an abort signal on the first encountered failure? Maybe the feature is already there and my quick glancing was not enough.

**Comment by silentbicycle** [comment]
I definitely would. If you haven't already implemented it, I'll probably add it myself, as part of the next release. That feature doesn't exist yet, but I have a good idea how it would fit into the existing implementation, and I agree that it's a good idea.
