### ISSUE TITLE
Typo in comment in greatest.h

### ISSUE THREAD

**Issue by orangewait** [silentbicycle/greatest#89]
Hello, I'm studying greatest and I'm gonna use it on my next project. Thanks for your work!

I've found a tiny pedantic issue in greatest.h : in the comment above the definition of GREATEST_ASSERT_STRN_EQm *strcmp* should be replaced with *str**n**cmp*

https://github.com/silentbicycle/greatest/blob/master/greatest.h#L542

Best Regards,
Danilo

**Comment by silentbicycle** [comment]
Thanks! It will be fixed in the next release.

Please let me know if you have any thoughts about general usability. Some things are a little tricky because I'm avoiding dynamic allocation and non-portable extensions (such as gcc's `typeof`), but otherwise I'm trying to make it easy to use.
